### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghoway** [mayeedwin/twitterbot#3]
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/twitterbot-master/bot.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

**Comment by mayeedwin** [comment]
Hey @ghoway 

**Run the following in the command line while in the ./bot folder directory**

```js
 node bot/bot.js
```

Or 

While in the root folder, run;

```js
 node bot/bot.js
```

Cheers!
