### ISSUE TITLE
how to change hashtag?

### ISSUE THREAD

**Issue by bulanbintang69** [mayeedwin/twitterbot#4]
how to change hashtags
I've tried replacing in bot.js
but can't.
and an error occurs

**Comment by bulanbintang69** [comment]
![Uploading Screenshot_2021-12-19-01-58-41-143_com.termux.jpg…]()

**Comment by bulanbintang69** [comment]
![Uploading Screenshot_2021-12-19-01-58-41-143_com.termux.jpg…]()

**Comment by bulanbintang69** [comment]
$ node bot.js
/data/data/com.termux/files/home/twitterbot/bot/bot.js:19
      const retweetId = data.statuses[0].id_str;
                                         ^

TypeError: Cannot read properties of undefined (reading 'id_str')
    at /data/data/com.termux/files/home/twitterbot/bot/bot.js:19:42
    at /data/data/com.termux/files/home/twitterbot/bot/node_modules/twit/lib/twitter.js:127:13
    at onRequestComplete (/data/data/com.termux/files/home/twitterbot/bot/node_modules/twit/lib/twitter.js:352:5)
    at Request.<anonymous> (/data/data/com.termux/files/home/twitterbot/bot/node_modules/twit/lib/twitter.js:364:7)
    at Request.emit (node:events:402:35)
    at Gunzip.<anonymous> (/data/data/com.termux/files/home/twitterbot/bot/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at Gunzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by wpa-3** [comment]
what line did you change to and from ?

**Comment by bulanbintang69** [comment]
bot.js line 8.
I just changed the hashtags, for example what was "#MeetMaye" to "#csgo"

**Comment by bulanbintang69** [comment]
how can i retweet with other hashtags?
I'm still confused and need guidance..

**Comment by venturaEffect** [comment]
Have you solved the issue?

**Comment by bulanbintang69** [comment]
> Apakah Anda memecahkan masalah?

nope

**Comment by mayeedwin** [comment]
Thanks @venturaEffect cc @bulanbintang69
